### ISSUE TITLE
Clean up vignette folder

### ISSUE THREAD

**Issue by Casey308** [STAT325-S24/BrothersKaramazov#8]
I've been adding a bunch of half stubbed out analyses to this folder.  At some point I should clean it up.  This issue is so I will do this eventually.

**Comment by nicholasjhorton** [comment]
Is this still pending? If not, can you please close it?

**Comment by Casey308** [comment]
Done with https://github.com/STAT325-S24/BrothersKaramazov/commit/5dbaaa4988ddace9e58f965c5cce610ca27fcdf9
